# AdvancedMcInfo by the Austrian Developer LauseggerDevelopment (lausi1793)
AdvancedMcInfo:
  skype: '&bReplace this with your Skype Name'
  ts3: '&bReplace this with your Teamspeak IP'
  website: '&bReplace this with your Website'
  vote: '&bReplace this with your Votelink'
  forum: '&bReplace this with your Forum Link'
  MinecraftServerIP: '&bReplace this with your Server IP'
